language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install --editable .

script: py.test tests
